
def additoin(x, y):
        x = 10
        y = 20
    
        print("Addition:", x + b)


try:
    additoin(10, 20)

#except Exception as error:
 #   print("There was an error", error.__class__)

except NameError:

    print("Error defining variables")

else:
    print( "the operation is successful")